App Refactoring I
TurtleBurney/naver-land-crawler pull request #15
Opened 2022-03-03 08:11 UTC by handal95

테스트 환경 준비를 위해서 `app/`의 파일 경로들을 일부 수정합니다.

변경사항
1. config 설정 파일 경로 수정 
2. `app/__init__.py` 의 소스 코드를 새로운 파일에 경로 수정
 Database와의 deprecated 문제때문에 일부 코드 남아있으니 수정 바람
3. `views/`의 blueprint 관련 변수들을 새로운 파일로 분리함
4. 일부 파일명이 수정됨

2022-03-03 15:35 UTC, YubeenSon requested changes
주석에 있는 오타 수정과 질문 답변 바랍니다!

2022-03-03 15:35 UTC, YubeenSon commented on app/__init__.py
> +# Deprecated
이 부분이 deprecated로 주석되어 있는 것은 db도 추후에 다른 폴더로 이동할 것이라는 뜻인가요??

2022-03-03 15:35 UTC, YubeenSon commented on app/main.py
> +# app/confconfig.py에서의 항목 불러옴
오타있어요!

2022-03-03 15:35 UTC, YubeenSon commented on app/source/db.py
> +    from app.views import main, issue, updated_info, building
혹시 이 부분은 함수 안에 있는 다른 이유가 있는 것인가요??

2022-03-05 07:03 UTC, handal95 commented on app/__init__.py
> +# Deprecated
넵 맞습니당 `database/`에서 현재 경로상의 db를 참조하고있어서 남겨두었습니다.

database쪽 수정하면서 분리해야할 것 같아요

2022-03-05 07:04 UTC, handal95 commented on app/source/db.py
> +    from app.views import main, issue, updated_info, building
함수 밖에 있을 이유가 없고, 기능상 청사진들을 등록하는 부분들을 별도로 분할했습니다

2022-03-06 14:15 UTC, YubeenSon approved these changes
수고하셨습니다:3

2022-03-06 14:15 UTC, merged