Crawl building data
TurtleBurney/naver-land-crawler pull request #16
Opened 2022-03-06 14:18 UTC by YubeenSon

기능
- 테이블 building에 들어갈 내용을 크롤링해옵니다.

2022-03-07 14:01 UTC, handal95 requested changes
받아라 폭탄!

2022-03-07 14:01 UTC, handal95 commented on crawler/naver.py
> +from urllib import request
Import 정렬 https://pypi.org/project/isort/ 문서 한번 확인해보면 좋을 것 같아요

Flask 는 어디서 사용중인가요?

2022-03-07 14:01 UTC, handal95 commented on crawler/naver.py
> +        print(building_name, total_household, lowest_floor, highest_floor, approval_date, total_deal, number_address, road_address, sep="\n")
수집 대상 객체에 대한 부분은 별도의 class 가 있으면 좋을 것 같아요.

2022-03-07 14:01 UTC, handal95 commented on crawler/naver.py
> +        floor["high"] = splitted_floor[1][:-1]
splitted_floor[1][:`-1`] 에서 -1 은 무슨 의미인가요?

2022-03-07 14:01 UTC, handal95 commented on crawler/naver.py
> +        print(building_name, total_household, lowest_floor, highest_floor, approval_date, total_deal, number_address, road_address, sep="\n")
print하는 부분은 filter와 직접적인 연관은 없으니, 별도의 함수를 만드는게 좋을 것 같아요

2022-03-07 14:01 UTC, handal95 commented on crawler/naver.py
> +    tags = crawler.filter_building_info_tags(soup)
soup은 crawler외부에 있는 이유가 있나요?

2022-03-07 14:01 UTC, handal95 commented on crawler/naver.py
> +        lump_address = tags["addresses"][2].text.split("addr")[1].split("realPriceInfoYn")[0]
lump는 무슨 뜻인가요?? 덩어리?

2022-03-07 14:01 UTC, handal95 commented on crawler/naver.py
> +        number_ver = lump_splitted[0][4:-2]
number_ver는 무슨 축약어인가요?

2022-03-07 14:01 UTC, handal95 commented on crawler/naver.py
> +        tags["addresses"] = soup.find_all('script', type='text/javascript')
address 복수인가요?

2022-03-07 14:01 UTC, handal95 commented on crawler/naver.py
> +        total_wolse = tags["prices"][2].text
의미상 구분되는 단위로 개행이 있으면 좋을 것 같아요

2022-03-07 14:01 UTC, handal95 commented on crawler/naver.py
> +    def filter_building_detail(self, tags) -> None:
이왕이면 다른 부분에도 동일하게 타입 힌팅이 있으면 좋을 것 같아요.

2022-03-07 14:03 UTC, YubeenSon commented on crawler/naver.py
> +from urllib import request
앗 Flask는 사용하지 않습니다! 삭제하려합니다.

2022-03-07 14:20 UTC, YubeenSon commented on crawler/naver.py
> +        floor["high"] = splitted_floor[1][:-1]
최저/고층을 "8/34층"형태로 보여주고 있어서
"/"를 기준으로 나눈 다음 고층 데이터에서 "층"이라는 글자를 떼기 위해 맨 마지막 요소를 제외하는 [:-1]를 사용하였습니다!

2022-03-07 14:22 UTC, handal95 commented on crawler/naver.py
> +        floor["high"] = splitted_floor[1][:-1]
> 최저/고층을 "8/34층"형태로 보여주고 있어서 "/"를 기준으로 나눈 다음 고층 데이터에서 "층"이라는 글자를 떼기 위해 맨 마지막 요소를 제외하는 [:-1]를 사용하였습니다!

층 외에 다른 표현이 없다면 regex 사용을 권장드려요
https://docs.python.org/ko/3/howto/regex.html

2022-03-07 14:25 UTC, YubeenSon commented on crawler/naver.py
> +    tags = crawler.filter_building_info_tags(soup)
특별한 이유는 없습니다..! 안에 넣어도 될 것 같아요!

2022-03-07 14:42 UTC, YubeenSon commented on crawler/naver.py
> +        tags["addresses"] = soup.find_all('script', type='text/javascript')
아니요! address는 단수, addresses는 복수입니당

2022-03-07 14:44 UTC, YubeenSon commented on crawler/naver.py
> +        number_ver = lump_splitted[0][4:-2]
몇 단계 거쳐 가느라 임시로 만든 변수인데 곧 없어질 예정입니다..:)
원래는 address에서 지번 번호를 의미하려했습니다

2022-03-07 14:44 UTC, YubeenSon commented on crawler/naver.py
> +        lump_address = tags["addresses"][2].text.split("addr")[1].split("realPriceInfoYn")[0]
lump는 덩어리로 정제 전 뜯어낸 덩어리를 지칭하고 있습니다!

2022-03-08 12:14 UTC, YubeenSon commented on crawler/naver.py
> +        print(building_name, total_household, lowest_floor, highest_floor, approval_date, total_deal, number_address, road_address, sep="\n")
object와 refiner 추가하였습니다!

2022-03-08 12:14 UTC, YubeenSon commented on crawler/naver.py
> +        print(building_name, total_household, lowest_floor, highest_floor, approval_date, total_deal, number_address, road_address, sep="\n")
필요한 부분은 아니라 삭제하였습니다!

2022-03-08 12:15 UTC, YubeenSon commented on crawler/naver.py
> +        total_wolse = tags["prices"][2].text
반영하였습니다:)

2022-03-08 12:15 UTC, YubeenSon commented on crawler/naver.py
> +    def filter_building_detail(self, tags) -> None:
적용하였습니다!

2022-03-08 12:24 UTC, handal95 requested changes

2022-03-08 12:24 UTC, handal95 commented on crawler/naver.py
> +        tags["addresses"] = soup.find_all('script', type='text/javascript')
`refiner.py`의 parse HTML과 차이점이 있나요?

아래의 `address_data` 함수도 그렇고 중복되는 코드들이 있는 것 같습니다

2022-03-08 12:24 UTC, handal95 commented on crawler/object/building.py
> +        self.total_wolse = data["prices"]["wolse"]
total_deal 은 거래 가격의 합인가요? 매매 계약의 갯수인가요?

2022-03-08 12:24 UTC, handal95 commented on crawler/naver.py
> +    crawler.filter_building_detail(tags)
코드가 중복되고 있는 것 같아요

2022-03-08 12:24 UTC, handal95 commented on crawler/object/building.py
> +            "total_wolse": self.total_wolse,
의미 구분당 개행이 있으면 좋을 것 같아요

2022-03-08 12:24 UTC, handal95 commented on crawler/object/building.py
> +        self.highest_floor = data["floors"]["high"]
lowest floor는 지하를 의미하나요?

2022-03-08 12:24 UTC, handal95 commented on crawler/object/refiner.py
> +        soup = BeautifulSoup(html, "html.parser")
`naver.py`에서도 soup을 이용하던데 중복되는 부분인지 확인 부탁드려요

2022-03-08 12:24 UTC, handal95 commented on crawler/object/refiner.py
> +            "details": soup.find_all("span", "detail_data_item"),
둘다 detail로 시작되는 태그에서 가져오는 것으로 보이는데, 
title은 별도로 title로 지정해둔 이유가 있을까요?

2022-03-08 12:24 UTC, handal95 commented on crawler/object/refiner.py
> +            "prices": self.price,
details : self.detail 과 같이 단복수 매칭이 안되는 것 같은데 확인 부탁드려요.

2022-03-08 12:46 UTC, YubeenSon commented on crawler/object/building.py
> +        self.total_wolse = data["prices"]["wolse"]
계약의 개수를 뜻합니다!

2022-03-08 12:49 UTC, YubeenSon commented on crawler/object/building.py
> +        self.highest_floor = data["floors"]["high"]
최저층을 뜻합니당
building에서의 최저층은 아파트의 건물이 여럿인데, 가장 낮은 층의 건물의 층수 가 최저층을 뜻하는 것 같습니다!

2022-03-08 12:54 UTC, YubeenSon commented on crawler/object/refiner.py
> +            "details": soup.find_all("span", "detail_data_item"),
일단 두 태그의 id는 달랐고 details에 담긴 승인날짜, 총 세대수, 모든 동의 개수는 하나로 묶을 단어가 잘 생각이 안 나서 detail로 묶었고,
detail_comlex_title엔 딱 건물명만 담기고 id에도 title이 언급되어있어 title로 변수명을 정하였습니다!

2022-03-08 13:32 UTC, YubeenSon commented on crawler/naver.py
> +        tags["addresses"] = soup.find_all('script', type='text/javascript')
naver.py 작업은 commit되었지 않아 방금 커밋했습니다..!

2022-03-08 13:59 UTC, handal95 requested changes
받아라 줄어드는 폭탄!

2022-03-08 13:59 UTC, handal95 commented on crawler/object/building.py
> +        self.highest_floor = data["floor"]["high"]
lowest floor 라면 의미가 분명하게 data["floor"]["lowest"] 이렇게 되어야 할 것 같아요.
highest도 동일합니다

2022-03-08 13:59 UTC, handal95 commented on crawler/object/building.py
> +        self.building_name = data["title"]["title"]
building_name 이 title-title에서 오는 부분이 명확하지 않은 것 같아요. 

둘 중 하나의 이름을 매칭할 필요가 있을 것 같습니다

2022-03-08 14:18 UTC, YubeenSon commented on crawler/object/building.py
> +        self.total_wolse = data["prices"]["wolse"]
total_{} -> {}_count로 변경되었습니다!

2022-03-08 14:18 UTC, YubeenSon commented on crawler/object/building.py
> +        self.highest_floor = data["floor"]["high"]
반영하였습니다!

2022-03-08 14:44 UTC, handal95 approved these changes
이번에는 폭탄이 없습니다 호호호 
블랙한번 적용해주시면 LGTM! 🚀

2022-03-08 14:45 UTC, merged