Refactoring DB
TurtleBurney/naver-land-crawler pull request #19
Opened 2022-03-11 15:12 UTC by YubeenSon

DB 관련 피드백을 반영합니다.
1. 모호한 변수명 변경(area, link, default_price...)
2. 자료형 변경(돈의 경우 String으로)
3. 참조, 역참조 관계 정립

2022-03-11 16:15 UTC, handal95 requested changes
전체적으로 nullable의 처리에 대해서 default가 있어야 할 부분과 nullable=False로 처리될 부분들이 명확했으면 좋겠ㅅ브니다!

2022-03-11 16:15 UTC, handal95 commented on app/views/building.py
> +    building = Building.query.get_or_404(building_id)
함수명은 동사인게 좋을 것 같아요

2022-03-11 16:15 UTC, handal95 commented on app/views/updated_info.py
> +    buildings = Building.query.all()
`building.py`와 동일해보이는데 합쳐도 되지 않을까요?

2022-03-11 16:15 UTC, handal95 commented on database/models/building.py
> +    total_wolse = db.Column(db.Integer, nullable=False)
거래, 전세, 월세 관련 변수 명칭이 지난 번에 수정되었던 것 같은데, 여기서는 다른 의미인가요?

3 종이 모두 False인 것 보다는 default=0 과 같은 방식이 좀 더 직관적일 것 같아요.

2022-03-11 16:15 UTC, handal95 commented on database/models/building.py
> +    total_dong = db.Column(db.Integer, nullable=False)
total의 명칭이 덜 직관적인 것 같아요. 어떤 total인가요?
현재 매매가 가능한 건물 동의 숫자인 것인지, 전체 단지내 동의 갯수인건지 궁금합니다.

hosuehold는 호수 인가요?

2022-03-11 16:15 UTC, handal95 commented on database/models/building.py
> +        db.Enum("A1", "B1", "B2", name="building_code_enum"), nullable=False
building code의 enum은 어떤건가요?

2022-03-11 16:15 UTC, handal95 commented on database/models/household.py
> +    updated_at = db.Column(db.DateTime(timezone=True), server_onupdate=func.now())
의미상 구분되는 단위별로 개행이 있으면 좀 더 보기 좋을 것 같아요.

2022-03-11 16:15 UTC, handal95 commented on database/models/household.py
> +    private_area = db.Column(db.Float, nullable=False)
nullable한 경우는 없나요? 다른 부분들도 마찬가지입니다

2022-03-11 16:15 UTC, handal95 commented on database/models/price.py
>      )
명칭이 Price (금액)으로 되어있는데 금액보다는 Contract 같은게 좀 더 어울릴 것 같아요.

2022-03-11 16:15 UTC, handal95 commented on database/models/price.py
> +    max_price = db.Column(db.String(50), nullable=False)
`max_price`의 nullable 이 False로 변경된 이유가 있을까요?

금액의 단위도 궁금합니다

2022-03-11 16:15 UTC, handal95 commented on database/models/region.py
> +        "Building", backref=db.backref("region", cascade="all, delete-orphan")
행정 지역이 변경되거나 사라졌을 때 전체 DB의 데이터가 삭제되는 건 위험할 것 같아요

2022-03-11 16:15 UTC, handal95 commented on database/models/region.py
> +
:P

2022-03-11 16:29 UTC, YubeenSon commented on app/views/building.py
> +    building = Building.query.get_or_404(building_id)
show_detail로 변경했습니다!

2022-03-11 16:30 UTC, YubeenSon commented on app/views/updated_info.py
> +    buildings = Building.query.all()
존재하는 페이지를 먼저 파일로 형성하는 것이 좋겠다는 생각이 들어 비슷한 페이지의 코드를 복사하여 임시로 `update_info.py`를 만들었습니다. 그런 의미에서 파일의 내용(함수)를 더 그 페이지에 맞게 변경하도록 하겠습니다!

2022-03-11 16:40 UTC, YubeenSon commented on database/models/building.py
> +    total_wolse = db.Column(db.Integer, nullable=False)
crawler 작업할때 xxx_count로 변경해둔 것 반영하였습니다!

2022-03-11 16:44 UTC, YubeenSon commented on database/models/building.py
> +        db.Enum("A1", "B1", "B2", name="building_code_enum"), nullable=False
앗 수정하다 잘못 내용이 들어간 부분이라 새로 고친 것을 봐주세요..!

2022-03-11 16:52 UTC, YubeenSon commented on database/models/building.py
> +    total_dong = db.Column(db.Integer, nullable=False)
단지 내 전체 동의 갯수여서 total을 사용하였습니다. 이 부분이 모호하다면 dong_count(동 개수)로 수정하겠습니다!
household는 세대를 뜻합니다. 그래서 total_household는 총 세대수를 뜻하려고 적은 것인데 모호하다면 동과 같이 _count로 변경하겠습니다!

2022-03-11 16:56 UTC, YubeenSon commented on database/models/household.py
> +    private_area = db.Column(db.Float, nullable=False)
현재로서 building을 제외하고는 0이라도 받아올 수 있는 부분들이어서 False로 지정하였습니다!

2022-03-11 17:01 UTC, YubeenSon commented on database/models/price.py
>      )
현재 Price 내의 컬럼들이 가격 정보만 갖고 있어서 Contract로 할 경우 계약에서 가격부분만 다루고 있어 대표성이 떨어질 것 같은데 이 부분에 대해서는 어떻게 생각하세요..?

2022-03-11 17:07 UTC, YubeenSon commented on database/models/price.py
> +    max_price = db.Column(db.String(50), nullable=False)
값이 범위 형태로 나타나는 경우를 대비해 max_price가 존재하는데 단일값이라면 min과 max에 같은 값을 넣으면 된다고 생각하여 False로 변경하였습니다! 
response로 전달되는 json 파일에서 저렇게 사용하고 있어 방식을 차용하였습니다..!

2022-03-11 17:10 UTC, YubeenSon commented on database/models/price.py
> +    max_price = db.Column(db.String(50), nullable=False)
아 단위는 만원 입니다! String의 크기가 너무 큰가요..?

2022-03-12 16:25 UTC, YubeenSon commented on app/views/updated_info.py
> +    buildings = Building.query.all()
생각해보니 현재 branch에서 하기엔 내용이 안 맞는데 TODO를 달아놓고 다음에 수정해도 괜찮을까요..?

2022-03-12 16:43 UTC, YubeenSon commented on database/models/price.py
> +    max_price = db.Column(db.String(50), nullable=False)
Price의 이름 대표성에 대한 논의 후 ContractPrice로 변경하였습니다:)

2022-03-12 16:43 UTC, YubeenSon commented on database/models/price.py
>      )
ContractPrice

2022-03-14 06:38 UTC, handal95 requested changes
점점점 줄어드는 폭탄!
고생이 많습니당!

2022-03-14 06:38 UTC, handal95 commented on database/models/price.py
> +    fk_house_id = db.Column(
household_id 를 의미하는 게 맞나요?

2022-03-14 06:38 UTC, handal95 commented on app/source/db.py
> +
이부분 없이도 잘 동작하는지 확인 부탁드려요~

2022-03-14 06:38 UTC, handal95 commented on database/models/contract_price.py
> +    fk_house_id = db.Column(
household_id 맞는지 확인 부탁드려요

2022-03-14 06:38 UTC, handal95 commented on database/models/contract_price.py
> +        db.Enum("Deal", "Jeonse", "Wolse", name="contract_type_enum"), nullable=False
Enum type의 고유값은 UPPER_CASE로 수정해주세요.

https://docs.python.org/ko/3/library/enum.html

2022-03-14 07:17 UTC, YubeenSon commented on app/source/db.py
> +
이 부분 주석처리하니 migration file 만드는 것에서 오류가 생겨서 유지하려합니다!

2022-03-14 07:17 UTC, YubeenSon commented on database/models/contract_price.py
> +    fk_house_id = db.Column(
넵 맞습니다 수정하겠습니다!

2022-03-14 08:10 UTC, YubeenSon commented on database/models/contract_price.py
> +        db.Enum("Deal", "Jeonse", "Wolse", name="contract_type_enum"), nullable=False
반영하였습니다~

2022-03-14 08:27 UTC, handal95 approved these changes
수고 많으셨습니다아아 🚀 🚀

2022-03-14 08:27 UTC, handal95 commented on app/source/db.py
> +
import해오고 아무런 연결을 해주는 부분이 없는데 오류가 난다는게 이상하네요 흠

2022-03-14 08:27 UTC, handal95 commented on app/source/db.py
> +
일단 알게씁니다 호호

2022-03-14 10:58 UTC, merged