Crawl Price
TurtleBurney/naver-land-crawler pull request #24
Opened 2022-04-08 08:19 UTC by YubeenSon

작업사항
* 개별 매물 정보를 파싱하는 부분을 `HouseholdCrawler`에서 분리하여 별도의 `HouseholdPriceResponse` 클래스로 이동하였습니다.
* `ContractPriceCrawler`를 통해 가격 정보를 받아와 `ContractPrice`객체에 담았습니다.

2022-04-08 09:49 UTC, handal95 commented on naver_land/crawler/contract_price.py
> +            contract_price_raw = contract_price_raw_list[i]
```suggestion
        for contract_price_raw in contract_price_raw_list:
            contract_price_raw = contract_price_raw_list[i]
```

2022-04-08 09:59 UTC, handal95 requested changes
전반적으로 Crawler의 역할과 Object 역할 사이에 혼동이 조금 있는것처럼 보입니당

2022-04-08 09:59 UTC, handal95 commented on naver_land/crawler/household_price_response.py
> +class HouseholdPriceResponse(BaseCrawler):
Crawler를 상속받는데, Crawler가 아닌것같네용

2022-04-08 09:59 UTC, handal95 commented on naver_land/crawler_run.py
> +                # print(f"{sale_type} {page_num}/{page_count} 진행")
log로 변경된 print문은 지워주세용

2022-04-08 09:59 UTC, handal95 commented on naver_land/crawler_run.py
> +log = init_logger()
```suggestion
logger = init_logger()
```

2022-04-08 09:59 UTC, handal95 commented on naver_land/crawler_run.py
> +                total_contract_prices += contract_price
위에서는 List에 추가하는 방식이 `contract_price_info.append(contract_price)`와 같은데
맞춰주면 좋을 것 같아용

2022-04-08 09:59 UTC, handal95 commented on naver_land/crawler_run.py
> +                )
아키텍쳐가 뭔가 이상한것 같아요
Crawler가 동작 수행하는게 아니라 개별 데이터를 담고있는건가요

2022-04-08 09:59 UTC, handal95 commented on naver_land/crawler/__init__.py
> +    HouseholdPriceResponse,
의미구분이 명확한게 아니라면 Import 패키지들과 순서를 맞추면 더 좋을 것 같아요

2022-04-08 13:49 UTC, YubeenSon commented on naver_land/crawler_run.py
> +                # print(f"{sale_type} {page_num}/{page_count} 진행")
넹!

2022-04-08 14:05 UTC, YubeenSon commented on naver_land/crawler_run.py
> +log = init_logger()
파일명과 겹쳐서 log라 했는데 `logger`로 변경해도 문제가 되지 않네요! `init_logger`라 했으니 `logger`로 바꾸겠습니다:3

2022-04-08 14:12 UTC, YubeenSon commented on naver_land/crawler_run.py
> +                total_contract_prices += contract_price
`contract_price_info.append(contract_price)`에서는 list에 `ContractPrice`라는 객체를 list에 요소로 넣는 과정이고, 여기서는 list들을 병합하는 과정이어서 `append`를 사용하면 원하는 동작을 하지 못하게 됩니다..!

2022-04-08 14:13 UTC, YubeenSon commented on naver_land/crawler/__init__.py
> +    HouseholdPriceResponse,
앗 이거 isort 돌린 결과인데 순서를 바꾸는 쪽으로 수정할까요??

2022-04-08 14:27 UTC, YubeenSon commented on naver_land/crawler_run.py
> +                )
으음 맞아요 저 변수들이 한 페이지에서 읽어온 각각 `Household`, `ContractPrice` 20개(혹은 이하)의 데이터를 갖고 있어요. response 받는 부분을 떼어내는 과정에서 이렇게 되었는데 추가적인 수정이 필요할까요..?

2022-04-08 18:01 UTC, YubeenSon commented
1. HouseholdContractPriceCrawler 이름 바꾸기
2. BuildingCrawler에서 sample 빼고 모든 건물 순회하기
3. Crawler dir에서 Crawler 아닌 애 빼기
4. Contract -> 어떤 것으로 바꾸기(Pricing..)
5. Price가 하위 카테고리가 되기(단독 엔티티 말고)

2022-04-09 08:32 UTC, handal95 requested changes

2022-04-09 08:32 UTC, handal95 commented on naver_land/crawler/__init__.py
> +    HouseholdPriceResponse,
import 해오는 부분과 `__all__` 의 변수 간의 순서 확인 부탁드려요

2022-04-09 08:32 UTC, handal95 commented on naver_land/crawler_run.py
> +log = init_logger()
log는 동사 logger는 명사니까 변수명은 명사로 맞춰주세요 + import logger랑 충돌이 된다면, 접두사/접미사 혹은 패키지 명을 수정하는 방향도 좋겠네용

2022-04-11 06:58 UTC, merged