Crawl specific data
TurtleBurney/naver-land-crawler pull request #7
Opened 2021-03-22 17:41 UTC by YubeenSon

건물의 세부적인 정보, 계약 정보 등 구체적인 정보를 크롤링하여 가져옵니다.

- 세부 정보 추출
(매물이 존재하는 건물에 접근하여 매매, 전세, 월세 정보의 계약정보와, 건물의 주소, 동, 호, 거래가 등의 건물정보 등을 추출하여 저장)

2021-03-24 15:45 UTC, handal95 commented
허윽 temporary commit for rebase..... hotfix할때 여기 와서 수정할께요 죄송죄송

2021-03-24 15:56 UTC, handal95 requested changes
아직 작성중인 것 같아서 일단 전체적으로
컨벤션과 중복부분만 중점적으로 확인했습니다.
f-string 방식 염두해두면 좋을 것 같고, xpath tag가져오는 부분들에서도 공통된 부분들 처리가 되면 좋을 것 같아요

2021-03-24 15:56 UTC, handal95 commented on app/client.py
> +        EC.element_to_be_clickable((By.XPATH, "{0}".format(xpath)))
format string 형식을  f-string 방식으로 하고 있으니까 수정하시면 좋을 것 같아요
```suggestion
        EC.element_to_be_clickable((By.XPATH, f"{xpath}"))
```
or
```suggestion
        EC.element_to_be_clickable(f"{By.XPATH}{xpath}")
```

2021-03-24 15:56 UTC, handal95 commented on app/client.py
> +    click_javascript_void(BASE_TAG + "div[3]/div[2]/div/div/table/tbody/tr[3]/td[2]/a", driver)
각 함수가 뭘 클릭하는건가요?? 주석이 있으면 더 좋을 것 같아요

+ 공통되는 부분들은 따로 빼도 좋을 것 같은데 태그가 의미하는게 뭔지 모르니까 일단 pass 할께용

2021-03-24 15:56 UTC, handal95 commented on app/client.py
>      BASE_TAG = "//*[@id='mapSearch']/div[2]/div[1]/section/div[1]/"
사용하는 코드인가요??

2021-03-24 15:56 UTC, handal95 commented on app/client.py
> +    return driver
위에서 사용하는 BASE_TAG 랑 다른건가요?
각 단위별로 주석이 있으면 좋을 것 같아요
+ f-string 양식으로 수정해주세요

2021-03-24 15:56 UTC, handal95 commented on app/client.py
> +    click_javascript_void("//*[@id='mapSearch']/div[2]/div[1]/section/div[2]/a", driver)
각 단위별로 주석이 있으면 좀 더 이해하기 쉬울 것 같아요
+ TAG 부분이 많이 겹치는 부분이 있는 것 같네요

2021-03-24 15:56 UTC, handal95 commented on app/crawler.py
> +            general_data[i].rent_count = 0
0일때는 크롤링에 안잡히는 건가요??

2021-03-24 15:56 UTC, handal95 commented on app/crawler.py
> +    road_address = driver.find_element_by_xpath("//*[@id='_basic_content_cd']/article[4]/div[2]/p[2]").text
//[@id='_basic_content_cd']/ 같은 부분들은 별도로 떼어도 될 것 같아요

2021-03-24 17:03 UTC, YubeenSon commented on app/crawler.py
> +    road_address = driver.find_element_by_xpath("//*[@id='_basic_content_cd']/article[4]/div[2]/p[2]").text
ID_TAG로 분리했습니다!

2021-03-24 17:04 UTC, YubeenSon commented on app/crawler.py
> +            general_data[i].rent_count = 0
0이 잡히네요..! 불필요한 부분이어서 삭제하였습니다!

2021-03-24 17:04 UTC, YubeenSon commented on app/client.py
> +    click_javascript_void("//*[@id='mapSearch']/div[2]/div[1]/section/div[2]/a", driver)
전체적인 주석 보강하였습니다!

2021-03-24 17:05 UTC, YubeenSon commented on app/client.py
> +    return driver
위의 BASE_TAG는 함수 분리 과정에서 삭제되지 않았던 것입니다!
두 태그는 동일하고 불필요한 부분에서는 삭제가 이루어졌습니당

2021-03-24 17:05 UTC, YubeenSon commented on app/client.py
> +        EC.element_to_be_clickable((By.XPATH, "{0}".format(xpath)))
반영하였습니다!

2021-03-28 08:56 UTC, handal95 requested changes
다와가네요 수고하셨습니다!

2021-03-28 08:56 UTC, handal95 commented on app/client.py
>      ).click()
클릭 시간을 조금 더 사람답게 500 ms 로 줘도 될 것 같아요.
크롤러의 목적은 정보를 빠르게 수집하는거기도 하지만
상대측 서버에 부하를 주게되면 IP가 밴될수도 있어요.

2021-03-28 08:56 UTC, handal95 commented on app/crawler.py
> +    count, for_sale = 0, 0
`for_sale`말고 다른 단어는 없을까요?

2021-03-28 08:56 UTC, handal95 commented on app/crawler.py
> +        built_year = driver.find_elements_by_class_name("data")[5].text
try 문 안에서 작업할 수도 있지 않을까요??

2021-03-28 08:56 UTC, handal95 commented on app/crawler.py
> +    return building_list
하나만 담고 리턴하는건가요?

2021-03-28 08:56 UTC, handal95 commented on app/run.py
> +    driver.quit()
cralwer 내부에 try / except 를 설정해줘서,
의도하지 않은 종료가 이루어졌을때도 driver.quit()이 동작할 수 있게 수정해주세요.

지금 방식은 정상적으로 프로그램이 흘러갔을 때만 driver가 종료되는 것 같아요

2021-03-28 08:56 UTC, handal95 commented on app/run.py
> +            building_list = crawl_buildings(driver)
`building_list`는 어디서 사용되고 있나요?

2021-03-28 08:56 UTC, handal95 commented on app/run.py
> +        if crawlable_list[i] == True:
Boolean이랑 비교할때는 주로 is True / is not False 같은 방식이 의미 흐름상 더 좋을 것 같아요,

2021-03-28 08:56 UTC, handal95 commented on app/crawler.py
> +    return len(quantities) // 3, crawlable_list
불필요한 정보들을 제거하고
crawlable_list에 True로 담기는 building 의 index만 저장하면 더 효율적일 것 같아요.

return 할때 전체 quantities를 확인할 필요도 없고,
나중에 crawl 대상을 선정할 때에도 crawlable_list에 담겨있는 index를 이용하면 될 것 같아요

2021-03-28 08:59 UTC, YubeenSon commented on app/client.py
>      ).click()
단위가 ms여서 실행시켜도 큰 지연은 없네요! 수정하였습니다.

2021-03-28 09:03 UTC, YubeenSon commented on app/crawler.py
> +    count, for_sale = 0, 0
`property_num` 명사형으로 변경하였습니다!

2021-03-28 09:07 UTC, YubeenSon commented on app/crawler.py
> +    return building_list
넵 반복문은 run.py에서 돌고 있어요! 
마지막 건물까지 담았을 때 전체 건물 정보를 보유한 배열을 리턴하고자하는 의도였습니당

2021-03-28 09:09 UTC, YubeenSon commented on app/run.py
> +        if crawlable_list[i] == True:
is True 좋군요 반영하였습니다!

2021-03-28 09:19 UTC, YubeenSon commented on app/crawler.py
> +    return len(quantities) // 3, crawlable_list
반영하였습니다!

2021-03-28 09:20 UTC, YubeenSon commented on app/crawler.py
> +        built_year = driver.find_elements_by_class_name("data")[5].text
try문 안에 넣어도 잘 동작하더군요! 안으로 수정해두었습니당

2021-03-28 09:36 UTC, YubeenSon commented on app/run.py
> +    driver.quit()
정상적으로 프로그램이 흘러가지 않을 때에도 driver이 종료되도록 WebDriverException import해오고 try문 활용해 수정하였습니다!

2021-03-28 09:37 UTC, YubeenSon commented on app/run.py
> +            building_list = crawl_buildings(driver)
아직은 사용되는 곳이 없습니다! 후에 DB 전송 전 형식을 맞추는 가공 과정에서 raw data역할을 할 것입니다

2021-03-28 15:17 UTC, handal95 commented on app/crawler.py
> +                crawlable_list.append(index // 3)
i
```suggestion
            crawlable = True if property_count > 0 else False
            if crawlable is True:
                crawlable_list.append(index // 3)
```

```
if property_count > 0:
    crawlable_list.append(index // 3)
```
로는 안되나요?

2021-03-28 15:24 UTC, handal95 requested changes

2021-03-28 15:24 UTC, handal95 commented on app/run.py
> +            driver.back()
뒤로 갔을 때 어떤 페이지가 나오는건가요?

2021-03-28 15:24 UTC, handal95 commented on app/run.py
> +        driver.quit()
driver quit을 먼저하고 로그를 남겨주세요

2021-03-28 15:50 UTC, YubeenSon commented on app/run.py
> +        driver.quit()
넵!!

2021-03-28 15:51 UTC, YubeenSon commented on app/run.py
> +            driver.back()
건물의 상세 정보 페이지에서 나가, 주소탭을 활성화할 수 있는 지도창으로 이동합니다!

2021-03-28 15:52 UTC, YubeenSon commented on app/crawler.py
> +                crawlable_list.append(index // 3)
이게 더 좋은 것 같아요 수정하겠습니다!

2021-03-28 15:59 UTC, handal95 approved these changes
🚀 정말 수고 많았습니다아아아

2021-03-28 16:32 UTC, merged

2021-03-28 16:32 UTC, YubeenSon commented
머지완료후!!!