Feature/class
TurtleBurney/naver-land-crawler pull request #9
Opened 2021-04-04 16:00 UTC by handal95

Crawler / Client / DB / Launcher의 각 개체를 class 화 합니다.

2021-04-06 14:03 UTC, YubeenSon requested changes
:param config: 부분 확인부탁드립니다!

2021-04-06 14:03 UTC, YubeenSon commented on app/client/db.py
> +        :param config: Molit Store 구성
param config가 적혀있는데 이 함수에 파라미터가 있나요..?

2021-04-06 14:03 UTC, YubeenSon commented on app/client/web.py
> +        return driver
궁금한건데, 여기서는 self.driver 안 해도 되나요??

2021-04-06 14:03 UTC, YubeenSon commented on launcher.py
> +        crawler.run()
궁금한 점으로, DEBUG모드인데 왜 load_config를 하는 것인가요??

2021-04-06 14:03 UTC, handal95 commented on app/client/db.py
> +        :param config: Molit Store 구성
앗 예전 코드에서 붙여오면서 따라왔네요. 수정하겠습니다~

2021-04-06 14:25 UTC, handal95 commented on launcher.py
> +        crawler.run()
CONFIG 파일은 항상 필요하니까요!
근데, 생각해보니 load_config파일을 외부 파라미터로 줄 필요가 없었네요

2021-04-06 14:29 UTC, handal95 commented on app/client/web.py
> +        return driver
self.driver는 해당 함수를 통해 생성되는 데,
생성 중간에 오류가 날 수도 있으니, 실제로 driver가 반환되거나 None 값이 반환되도록 설정했습니다

2021-04-11 14:39 UTC, YubeenSon approved these changes
수고하셨습니다~~

2021-04-11 14:40 UTC, merged